import i1 from "./tiny/1.png"
import i10 from "./tiny/10.png"
import i2 from "./tiny/2.png"
import i3 from "./tiny/3.png"
import i4 from "./tiny/4.png"
import i5 from "./tiny/5.png"
import i6 from "./tiny/6.png"
import i7 from "./tiny/7.png"
import i8 from "./tiny/8.png"
import i9 from "./tiny/9.png"
export const imgs = [i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,]